// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: proto/service/service.proto

package service

import (
	context "context"
	command "github.com/hexenlabs/edr/server/proto/command"
	common "github.com/hexenlabs/edr/server/proto/common"
	telemetry "github.com/hexenlabs/edr/server/proto/telemetry"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EDRService_StreamTelemetry_FullMethodName    = "/hexen.service.EDRService/StreamTelemetry"
	EDRService_CommandChannel_FullMethodName     = "/hexen.service.EDRService/CommandChannel"
	EDRService_GetPendingCommands_FullMethodName = "/hexen.service.EDRService/GetPendingCommands"
	EDRService_Heartbeat_FullMethodName          = "/hexen.service.EDRService/Heartbeat"
)

// EDRServiceClient is the client API for EDRService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EDRServiceClient interface {
	// Agent -> Server: Stream telemetry events
	StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[telemetry.TelemetryBatch, common.StatusResponse], error)
	// Bidirectional stream for C2
	// Server pushes Commands, Agent pushes CommandResponses
	CommandChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[command.CommandResponse, command.Command], error)
	// Explicit polling method for simplicity in MVP (Agent asks "Do you have work?")
	GetPendingCommands(ctx context.Context, in *common.AgentIdentity, opts ...grpc.CallOption) (*command.Command, error)
	// Simple heartbeat to keep connection alive and update status
	Heartbeat(ctx context.Context, in *common.AgentIdentity, opts ...grpc.CallOption) (*common.StatusResponse, error)
}

type eDRServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEDRServiceClient(cc grpc.ClientConnInterface) EDRServiceClient {
	return &eDRServiceClient{cc}
}

func (c *eDRServiceClient) StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[telemetry.TelemetryBatch, common.StatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EDRService_ServiceDesc.Streams[0], EDRService_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[telemetry.TelemetryBatch, common.StatusResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EDRService_StreamTelemetryClient = grpc.ClientStreamingClient[telemetry.TelemetryBatch, common.StatusResponse]

func (c *eDRServiceClient) CommandChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[command.CommandResponse, command.Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EDRService_ServiceDesc.Streams[1], EDRService_CommandChannel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[command.CommandResponse, command.Command]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EDRService_CommandChannelClient = grpc.BidiStreamingClient[command.CommandResponse, command.Command]

func (c *eDRServiceClient) GetPendingCommands(ctx context.Context, in *common.AgentIdentity, opts ...grpc.CallOption) (*command.Command, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(command.Command)
	err := c.cc.Invoke(ctx, EDRService_GetPendingCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eDRServiceClient) Heartbeat(ctx context.Context, in *common.AgentIdentity, opts ...grpc.CallOption) (*common.StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.StatusResponse)
	err := c.cc.Invoke(ctx, EDRService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EDRServiceServer is the server API for EDRService service.
// All implementations must embed UnimplementedEDRServiceServer
// for forward compatibility.
type EDRServiceServer interface {
	// Agent -> Server: Stream telemetry events
	StreamTelemetry(grpc.ClientStreamingServer[telemetry.TelemetryBatch, common.StatusResponse]) error
	// Bidirectional stream for C2
	// Server pushes Commands, Agent pushes CommandResponses
	CommandChannel(grpc.BidiStreamingServer[command.CommandResponse, command.Command]) error
	// Explicit polling method for simplicity in MVP (Agent asks "Do you have work?")
	GetPendingCommands(context.Context, *common.AgentIdentity) (*command.Command, error)
	// Simple heartbeat to keep connection alive and update status
	Heartbeat(context.Context, *common.AgentIdentity) (*common.StatusResponse, error)
	mustEmbedUnimplementedEDRServiceServer()
}

// UnimplementedEDRServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEDRServiceServer struct{}

func (UnimplementedEDRServiceServer) StreamTelemetry(grpc.ClientStreamingServer[telemetry.TelemetryBatch, common.StatusResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedEDRServiceServer) CommandChannel(grpc.BidiStreamingServer[command.CommandResponse, command.Command]) error {
	return status.Error(codes.Unimplemented, "method CommandChannel not implemented")
}
func (UnimplementedEDRServiceServer) GetPendingCommands(context.Context, *common.AgentIdentity) (*command.Command, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingCommands not implemented")
}
func (UnimplementedEDRServiceServer) Heartbeat(context.Context, *common.AgentIdentity) (*common.StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedEDRServiceServer) mustEmbedUnimplementedEDRServiceServer() {}
func (UnimplementedEDRServiceServer) testEmbeddedByValue()                    {}

// UnsafeEDRServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EDRServiceServer will
// result in compilation errors.
type UnsafeEDRServiceServer interface {
	mustEmbedUnimplementedEDRServiceServer()
}

func RegisterEDRServiceServer(s grpc.ServiceRegistrar, srv EDRServiceServer) {
	// If the following call panics, it indicates UnimplementedEDRServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EDRService_ServiceDesc, srv)
}

func _EDRService_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EDRServiceServer).StreamTelemetry(&grpc.GenericServerStream[telemetry.TelemetryBatch, common.StatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EDRService_StreamTelemetryServer = grpc.ClientStreamingServer[telemetry.TelemetryBatch, common.StatusResponse]

func _EDRService_CommandChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EDRServiceServer).CommandChannel(&grpc.GenericServerStream[command.CommandResponse, command.Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EDRService_CommandChannelServer = grpc.BidiStreamingServer[command.CommandResponse, command.Command]

func _EDRService_GetPendingCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.AgentIdentity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EDRServiceServer).GetPendingCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EDRService_GetPendingCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EDRServiceServer).GetPendingCommands(ctx, req.(*common.AgentIdentity))
	}
	return interceptor(ctx, in, info, handler)
}

func _EDRService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.AgentIdentity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EDRServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EDRService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EDRServiceServer).Heartbeat(ctx, req.(*common.AgentIdentity))
	}
	return interceptor(ctx, in, info, handler)
}

// EDRService_ServiceDesc is the grpc.ServiceDesc for EDRService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EDRService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hexen.service.EDRService",
	HandlerType: (*EDRServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPendingCommands",
			Handler:    _EDRService_GetPendingCommands_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _EDRService_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _EDRService_StreamTelemetry_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "CommandChannel",
			Handler:       _EDRService_CommandChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/service/service.proto",
}
