// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/telemetry/telemetry.proto

package telemetry

import (
	common "github.com/hexenlabs/edr/server/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *common.AgentIdentity  `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Events        []*TelemetryEvent      `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryBatch) Reset() {
	*x = TelemetryBatch{}
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatch) ProtoMessage() {}

func (x *TelemetryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatch.ProtoReflect.Descriptor instead.
func (*TelemetryBatch) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryBatch) GetAgent() *common.AgentIdentity {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *TelemetryBatch) GetEvents() []*TelemetryEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type TelemetryEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp *common.Timestamp      `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventId   string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // Unique ID for deduplication
	// Types that are valid to be assigned to Event:
	//
	//	*TelemetryEvent_ProcessExec
	//	*TelemetryEvent_NetworkConn
	//	*TelemetryEvent_FileMod
	Event         isTelemetryEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryEvent) Reset() {
	*x = TelemetryEvent{}
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEvent) ProtoMessage() {}

func (x *TelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEvent.ProtoReflect.Descriptor instead.
func (*TelemetryEvent) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryEvent) GetTimestamp() *common.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TelemetryEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *TelemetryEvent) GetEvent() isTelemetryEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TelemetryEvent) GetProcessExec() *ProcessExec {
	if x != nil {
		if x, ok := x.Event.(*TelemetryEvent_ProcessExec); ok {
			return x.ProcessExec
		}
	}
	return nil
}

func (x *TelemetryEvent) GetNetworkConn() *NetworkConnection {
	if x != nil {
		if x, ok := x.Event.(*TelemetryEvent_NetworkConn); ok {
			return x.NetworkConn
		}
	}
	return nil
}

func (x *TelemetryEvent) GetFileMod() *FileModification {
	if x != nil {
		if x, ok := x.Event.(*TelemetryEvent_FileMod); ok {
			return x.FileMod
		}
	}
	return nil
}

type isTelemetryEvent_Event interface {
	isTelemetryEvent_Event()
}

type TelemetryEvent_ProcessExec struct {
	ProcessExec *ProcessExec `protobuf:"bytes,3,opt,name=process_exec,json=processExec,proto3,oneof"`
}

type TelemetryEvent_NetworkConn struct {
	NetworkConn *NetworkConnection `protobuf:"bytes,4,opt,name=network_conn,json=networkConn,proto3,oneof"`
}

type TelemetryEvent_FileMod struct {
	FileMod *FileModification `protobuf:"bytes,5,opt,name=file_mod,json=fileMod,proto3,oneof"` // Future: Registry, DNS, etc.
}

func (*TelemetryEvent_ProcessExec) isTelemetryEvent_Event() {}

func (*TelemetryEvent_NetworkConn) isTelemetryEvent_Event() {}

func (*TelemetryEvent_FileMod) isTelemetryEvent_Event() {}

type ProcessExec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Pid             int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid            int32                  `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	ImagePath       string                 `protobuf:"bytes,3,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	CommandLine     string                 `protobuf:"bytes,4,opt,name=command_line,json=commandLine,proto3" json:"command_line,omitempty"`
	User            string                 `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	ParentImagePath string                 `protobuf:"bytes,6,opt,name=parent_image_path,json=parentImagePath,proto3" json:"parent_image_path,omitempty"`
	Sha256Hash      string                 `protobuf:"bytes,7,opt,name=sha256_hash,json=sha256Hash,proto3" json:"sha256_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessExec) Reset() {
	*x = ProcessExec{}
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessExec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessExec) ProtoMessage() {}

func (x *ProcessExec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessExec.ProtoReflect.Descriptor instead.
func (*ProcessExec) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessExec) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessExec) GetPpid() int32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessExec) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *ProcessExec) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

func (x *ProcessExec) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ProcessExec) GetParentImagePath() string {
	if x != nil {
		return x.ParentImagePath
	}
	return ""
}

func (x *ProcessExec) GetSha256Hash() string {
	if x != nil {
		return x.Sha256Hash
	}
	return ""
}

type NetworkConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	ImagePath     string                 `protobuf:"bytes,2,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	LocalAddress  string                 `protobuf:"bytes,3,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	LocalPort     int32                  `protobuf:"varint,4,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	RemoteAddress string                 `protobuf:"bytes,5,opt,name=remote_address,json=remoteAddress,proto3" json:"remote_address,omitempty"`
	RemotePort    int32                  `protobuf:"varint,6,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,7,opt,name=protocol,proto3" json:"protocol,omitempty"`   // TCP/UDP
	Direction     string                 `protobuf:"bytes,8,opt,name=direction,proto3" json:"direction,omitempty"` // INBOUND/OUTBOUND
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConnection) Reset() {
	*x = NetworkConnection{}
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConnection) ProtoMessage() {}

func (x *NetworkConnection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConnection.ProtoReflect.Descriptor instead.
func (*NetworkConnection) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkConnection) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *NetworkConnection) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *NetworkConnection) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

func (x *NetworkConnection) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *NetworkConnection) GetRemoteAddress() string {
	if x != nil {
		return x.RemoteAddress
	}
	return ""
}

func (x *NetworkConnection) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *NetworkConnection) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetworkConnection) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type FileModification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	ImagePath     string                 `protobuf:"bytes,2,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"` // Process that touched the file
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`                           // CREATE, MODIFY, DELETE, RENAME
	Sha256Hash    string                 `protobuf:"bytes,5,opt,name=sha256_hash,json=sha256Hash,proto3" json:"sha256_hash,omitempty"` // If applicable (e.g. on create/modify close)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileModification) Reset() {
	*x = FileModification{}
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileModification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileModification) ProtoMessage() {}

func (x *FileModification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileModification.ProtoReflect.Descriptor instead.
func (*FileModification) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *FileModification) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *FileModification) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *FileModification) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileModification) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *FileModification) GetSha256Hash() string {
	if x != nil {
		return x.Sha256Hash
	}
	return ""
}

var File_proto_telemetry_telemetry_proto protoreflect.FileDescriptor

const file_proto_telemetry_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/telemetry/telemetry.proto\x12\x0fhexen.telemetry\x1a\x19proto/common/common.proto\"|\n" +
	"\x0eTelemetryBatch\x121\n" +
	"\x05agent\x18\x01 \x01(\v2\x1b.hexen.common.AgentIdentityR\x05agent\x127\n" +
	"\x06events\x18\x02 \x03(\v2\x1f.hexen.telemetry.TelemetryEventR\x06events\"\xb7\x02\n" +
	"\x0eTelemetryEvent\x125\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x17.hexen.common.TimestampR\ttimestamp\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12A\n" +
	"\fprocess_exec\x18\x03 \x01(\v2\x1c.hexen.telemetry.ProcessExecH\x00R\vprocessExec\x12G\n" +
	"\fnetwork_conn\x18\x04 \x01(\v2\".hexen.telemetry.NetworkConnectionH\x00R\vnetworkConn\x12>\n" +
	"\bfile_mod\x18\x05 \x01(\v2!.hexen.telemetry.FileModificationH\x00R\afileModB\a\n" +
	"\x05event\"\xd6\x01\n" +
	"\vProcessExec\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\x05R\x04ppid\x12\x1d\n" +
	"\n" +
	"image_path\x18\x03 \x01(\tR\timagePath\x12!\n" +
	"\fcommand_line\x18\x04 \x01(\tR\vcommandLine\x12\x12\n" +
	"\x04user\x18\x05 \x01(\tR\x04user\x12*\n" +
	"\x11parent_image_path\x18\x06 \x01(\tR\x0fparentImagePath\x12\x1f\n" +
	"\vsha256_hash\x18\a \x01(\tR\n" +
	"sha256Hash\"\x8a\x02\n" +
	"\x11NetworkConnection\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x1d\n" +
	"\n" +
	"image_path\x18\x02 \x01(\tR\timagePath\x12#\n" +
	"\rlocal_address\x18\x03 \x01(\tR\flocalAddress\x12\x1d\n" +
	"\n" +
	"local_port\x18\x04 \x01(\x05R\tlocalPort\x12%\n" +
	"\x0eremote_address\x18\x05 \x01(\tR\rremoteAddress\x12\x1f\n" +
	"\vremote_port\x18\x06 \x01(\x05R\n" +
	"remotePort\x12\x1a\n" +
	"\bprotocol\x18\a \x01(\tR\bprotocol\x12\x1c\n" +
	"\tdirection\x18\b \x01(\tR\tdirection\"\x99\x01\n" +
	"\x10FileModification\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x1d\n" +
	"\n" +
	"image_path\x18\x02 \x01(\tR\timagePath\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1f\n" +
	"\vsha256_hash\x18\x05 \x01(\tR\n" +
	"sha256HashB1Z/github.com/hexenlabs/edr/server/proto/telemetryb\x06proto3"

var (
	file_proto_telemetry_telemetry_proto_rawDescOnce sync.Once
	file_proto_telemetry_telemetry_proto_rawDescData []byte
)

func file_proto_telemetry_telemetry_proto_rawDescGZIP() []byte {
	file_proto_telemetry_telemetry_proto_rawDescOnce.Do(func() {
		file_proto_telemetry_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_telemetry_telemetry_proto_rawDesc), len(file_proto_telemetry_telemetry_proto_rawDesc)))
	})
	return file_proto_telemetry_telemetry_proto_rawDescData
}

var file_proto_telemetry_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_telemetry_telemetry_proto_goTypes = []any{
	(*TelemetryBatch)(nil),       // 0: hexen.telemetry.TelemetryBatch
	(*TelemetryEvent)(nil),       // 1: hexen.telemetry.TelemetryEvent
	(*ProcessExec)(nil),          // 2: hexen.telemetry.ProcessExec
	(*NetworkConnection)(nil),    // 3: hexen.telemetry.NetworkConnection
	(*FileModification)(nil),     // 4: hexen.telemetry.FileModification
	(*common.AgentIdentity)(nil), // 5: hexen.common.AgentIdentity
	(*common.Timestamp)(nil),     // 6: hexen.common.Timestamp
}
var file_proto_telemetry_telemetry_proto_depIdxs = []int32{
	5, // 0: hexen.telemetry.TelemetryBatch.agent:type_name -> hexen.common.AgentIdentity
	1, // 1: hexen.telemetry.TelemetryBatch.events:type_name -> hexen.telemetry.TelemetryEvent
	6, // 2: hexen.telemetry.TelemetryEvent.timestamp:type_name -> hexen.common.Timestamp
	2, // 3: hexen.telemetry.TelemetryEvent.process_exec:type_name -> hexen.telemetry.ProcessExec
	3, // 4: hexen.telemetry.TelemetryEvent.network_conn:type_name -> hexen.telemetry.NetworkConnection
	4, // 5: hexen.telemetry.TelemetryEvent.file_mod:type_name -> hexen.telemetry.FileModification
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_telemetry_telemetry_proto_init() }
func file_proto_telemetry_telemetry_proto_init() {
	if File_proto_telemetry_telemetry_proto != nil {
		return
	}
	file_proto_telemetry_telemetry_proto_msgTypes[1].OneofWrappers = []any{
		(*TelemetryEvent_ProcessExec)(nil),
		(*TelemetryEvent_NetworkConn)(nil),
		(*TelemetryEvent_FileMod)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_telemetry_telemetry_proto_rawDesc), len(file_proto_telemetry_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_telemetry_telemetry_proto_goTypes,
		DependencyIndexes: file_proto_telemetry_telemetry_proto_depIdxs,
		MessageInfos:      file_proto_telemetry_telemetry_proto_msgTypes,
	}.Build()
	File_proto_telemetry_telemetry_proto = out.File
	file_proto_telemetry_telemetry_proto_goTypes = nil
	file_proto_telemetry_telemetry_proto_depIdxs = nil
}
