// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/command/command.proto

package command

import (
	common "github.com/hexenlabs/edr/server/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_CMD_UNKNOWN      CommandType = 0
	CommandType_CMD_SHELL        CommandType = 1
	CommandType_CMD_FILE_OP      CommandType = 2
	CommandType_CMD_PROCESS_KILL CommandType = 3
	CommandType_CMD_ISOLATION    CommandType = 4
	CommandType_CMD_AGENT_UPDATE CommandType = 5
	CommandType_CMD_OSQUERY      CommandType = 6
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "CMD_UNKNOWN",
		1: "CMD_SHELL",
		2: "CMD_FILE_OP",
		3: "CMD_PROCESS_KILL",
		4: "CMD_ISOLATION",
		5: "CMD_AGENT_UPDATE",
		6: "CMD_OSQUERY",
	}
	CommandType_value = map[string]int32{
		"CMD_UNKNOWN":      0,
		"CMD_SHELL":        1,
		"CMD_FILE_OP":      2,
		"CMD_PROCESS_KILL": 3,
		"CMD_ISOLATION":    4,
		"CMD_AGENT_UPDATE": 5,
		"CMD_OSQUERY":      6,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_command_command_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_proto_command_command_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_command_command_proto_rawDescGZIP(), []int{0}
}

type Command struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	CreatedAt *common.Timestamp      `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Type      CommandType            `protobuf:"varint,3,opt,name=type,proto3,enum=hexen.command.CommandType" json:"type,omitempty"`
	// Commands must be signed by the admin's private key.
	// The agent verifies this signature before execution.
	Signature []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Command_Shell
	//	*Command_FileOp
	//	*Command_ProcessKill
	//	*Command_Isolation
	//	*Command_Osquery
	Payload       isCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_command_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_command_command_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetCreatedAt() *common.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_CMD_UNKNOWN
}

func (x *Command) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Command) GetPayload() isCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetShell() *ShellCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_Shell); ok {
			return x.Shell
		}
	}
	return nil
}

func (x *Command) GetFileOp() *FileOpCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_FileOp); ok {
			return x.FileOp
		}
	}
	return nil
}

func (x *Command) GetProcessKill() *ProcessKillCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_ProcessKill); ok {
			return x.ProcessKill
		}
	}
	return nil
}

func (x *Command) GetIsolation() *IsolationCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_Isolation); ok {
			return x.Isolation
		}
	}
	return nil
}

func (x *Command) GetOsquery() *OsqueryCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_Osquery); ok {
			return x.Osquery
		}
	}
	return nil
}

type isCommand_Payload interface {
	isCommand_Payload()
}

type Command_Shell struct {
	Shell *ShellCommand `protobuf:"bytes,5,opt,name=shell,proto3,oneof"`
}

type Command_FileOp struct {
	FileOp *FileOpCommand `protobuf:"bytes,6,opt,name=file_op,json=fileOp,proto3,oneof"`
}

type Command_ProcessKill struct {
	ProcessKill *ProcessKillCommand `protobuf:"bytes,7,opt,name=process_kill,json=processKill,proto3,oneof"`
}

type Command_Isolation struct {
	Isolation *IsolationCommand `protobuf:"bytes,8,opt,name=isolation,proto3,oneof"`
}

type Command_Osquery struct {
	Osquery *OsqueryCommand `protobuf:"bytes,9,opt,name=osquery,proto3,oneof"`
}

func (*Command_Shell) isCommand_Payload() {}

func (*Command_FileOp) isCommand_Payload() {}

func (*Command_ProcessKill) isCommand_Payload() {}

func (*Command_Isolation) isCommand_Payload() {}

func (*Command_Osquery) isCommand_Payload() {}

type ShellCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Script        string                 `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`                        // PowerShell, Bash, Zsh
	ShellType     string                 `protobuf:"bytes,2,opt,name=shell_type,json=shellType,proto3" json:"shell_type,omitempty"` // "powershell", "cmd", "bash", "sh"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellCommand) Reset() {
	*x = ShellCommand{}
	mi := &file_proto_command_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellCommand) ProtoMessage() {}

func (x *ShellCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellCommand.ProtoReflect.Descriptor instead.
func (*ShellCommand) Descriptor() ([]byte, []int) {
	return file_proto_command_command_proto_rawDescGZIP(), []int{1}
}

func (x *ShellCommand) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *ShellCommand) GetShellType() string {
	if x != nil {
		return x.ShellType
	}
	return ""
}

type FileOpCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"` // "delete", "fetch", "quarantine"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOpCommand) Reset() {
	*x = FileOpCommand{}
	mi := &file_proto_command_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOpCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOpCommand) ProtoMessage() {}

func (x *FileOpCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOpCommand.ProtoReflect.Descriptor instead.
func (*FileOpCommand) Descriptor() ([]byte, []int) {
	return file_proto_command_command_proto_rawDescGZIP(), []int{2}
}

func (x *FileOpCommand) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileOpCommand) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type ProcessKillCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessKillCommand) Reset() {
	*x = ProcessKillCommand{}
	mi := &file_proto_command_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessKillCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessKillCommand) ProtoMessage() {}

func (x *ProcessKillCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessKillCommand.ProtoReflect.Descriptor instead.
func (*ProcessKillCommand) Descriptor() ([]byte, []int) {
	return file_proto_command_command_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessKillCommand) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessKillCommand) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type IsolationCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`                          // true = isolate, false = restore
	AllowedIps    []string               `protobuf:"bytes,2,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"` // IPs allowed during isolation (e.g. C2 IP)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsolationCommand) Reset() {
	*x = IsolationCommand{}
	mi := &file_proto_command_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsolationCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsolationCommand) ProtoMessage() {}

func (x *IsolationCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsolationCommand.ProtoReflect.Descriptor instead.
func (*IsolationCommand) Descriptor() ([]byte, []int) {
	return file_proto_command_command_proto_rawDescGZIP(), []int{4}
}

func (x *IsolationCommand) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *IsolationCommand) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

type OsqueryCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Query          string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"` // e.g. "SELECT * FROM processes"
	TimeoutSeconds int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OsqueryCommand) Reset() {
	*x = OsqueryCommand{}
	mi := &file_proto_command_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OsqueryCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OsqueryCommand) ProtoMessage() {}

func (x *OsqueryCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OsqueryCommand.ProtoReflect.Descriptor instead.
func (*OsqueryCommand) Descriptor() ([]byte, []int) {
	return file_proto_command_command_proto_rawDescGZIP(), []int{5}
}

func (x *OsqueryCommand) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *OsqueryCommand) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status        common.Status          `protobuf:"varint,2,opt,name=status,proto3,enum=hexen.common.Status" json:"status,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"` // Stdout/Stderr or JSON result from osquery
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CompletedAt   *common.Timestamp      `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_proto_command_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_command_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_command_command_proto_rawDescGZIP(), []int{6}
}

func (x *CommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResponse) GetStatus() common.Status {
	if x != nil {
		return x.Status
	}
	return common.Status(0)
}

func (x *CommandResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CommandResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CommandResponse) GetCompletedAt() *common.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

var File_proto_command_command_proto protoreflect.FileDescriptor

const file_proto_command_command_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/command/command.proto\x12\rhexen.command\x1a\x19proto/common/common.proto\"\xeb\x03\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x126\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x17.hexen.common.TimestampR\tcreatedAt\x12.\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1a.hexen.command.CommandTypeR\x04type\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x123\n" +
	"\x05shell\x18\x05 \x01(\v2\x1b.hexen.command.ShellCommandH\x00R\x05shell\x127\n" +
	"\afile_op\x18\x06 \x01(\v2\x1c.hexen.command.FileOpCommandH\x00R\x06fileOp\x12F\n" +
	"\fprocess_kill\x18\a \x01(\v2!.hexen.command.ProcessKillCommandH\x00R\vprocessKill\x12?\n" +
	"\tisolation\x18\b \x01(\v2\x1f.hexen.command.IsolationCommandH\x00R\tisolation\x129\n" +
	"\aosquery\x18\t \x01(\v2\x1d.hexen.command.OsqueryCommandH\x00R\aosqueryB\t\n" +
	"\apayload\"E\n" +
	"\fShellCommand\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\x12\x1d\n" +
	"\n" +
	"shell_type\x18\x02 \x01(\tR\tshellType\"A\n" +
	"\rFileOpCommand\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\"<\n" +
	"\x12ProcessKillCommand\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"K\n" +
	"\x10IsolationCommand\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12\x1f\n" +
	"\vallowed_ips\x18\x02 \x03(\tR\n" +
	"allowedIps\"O\n" +
	"\x0eOsqueryCommand\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\"\xd7\x01\n" +
	"\x0fCommandResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.hexen.common.StatusR\x06status\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12:\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x17.hexen.common.TimestampR\vcompletedAt*\x8e\x01\n" +
	"\vCommandType\x12\x0f\n" +
	"\vCMD_UNKNOWN\x10\x00\x12\r\n" +
	"\tCMD_SHELL\x10\x01\x12\x0f\n" +
	"\vCMD_FILE_OP\x10\x02\x12\x14\n" +
	"\x10CMD_PROCESS_KILL\x10\x03\x12\x11\n" +
	"\rCMD_ISOLATION\x10\x04\x12\x14\n" +
	"\x10CMD_AGENT_UPDATE\x10\x05\x12\x0f\n" +
	"\vCMD_OSQUERY\x10\x06B/Z-github.com/hexenlabs/edr/server/proto/commandb\x06proto3"

var (
	file_proto_command_command_proto_rawDescOnce sync.Once
	file_proto_command_command_proto_rawDescData []byte
)

func file_proto_command_command_proto_rawDescGZIP() []byte {
	file_proto_command_command_proto_rawDescOnce.Do(func() {
		file_proto_command_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_command_command_proto_rawDesc), len(file_proto_command_command_proto_rawDesc)))
	})
	return file_proto_command_command_proto_rawDescData
}

var file_proto_command_command_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_command_command_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_command_command_proto_goTypes = []any{
	(CommandType)(0),           // 0: hexen.command.CommandType
	(*Command)(nil),            // 1: hexen.command.Command
	(*ShellCommand)(nil),       // 2: hexen.command.ShellCommand
	(*FileOpCommand)(nil),      // 3: hexen.command.FileOpCommand
	(*ProcessKillCommand)(nil), // 4: hexen.command.ProcessKillCommand
	(*IsolationCommand)(nil),   // 5: hexen.command.IsolationCommand
	(*OsqueryCommand)(nil),     // 6: hexen.command.OsqueryCommand
	(*CommandResponse)(nil),    // 7: hexen.command.CommandResponse
	(*common.Timestamp)(nil),   // 8: hexen.common.Timestamp
	(common.Status)(0),         // 9: hexen.common.Status
}
var file_proto_command_command_proto_depIdxs = []int32{
	8, // 0: hexen.command.Command.created_at:type_name -> hexen.common.Timestamp
	0, // 1: hexen.command.Command.type:type_name -> hexen.command.CommandType
	2, // 2: hexen.command.Command.shell:type_name -> hexen.command.ShellCommand
	3, // 3: hexen.command.Command.file_op:type_name -> hexen.command.FileOpCommand
	4, // 4: hexen.command.Command.process_kill:type_name -> hexen.command.ProcessKillCommand
	5, // 5: hexen.command.Command.isolation:type_name -> hexen.command.IsolationCommand
	6, // 6: hexen.command.Command.osquery:type_name -> hexen.command.OsqueryCommand
	9, // 7: hexen.command.CommandResponse.status:type_name -> hexen.common.Status
	8, // 8: hexen.command.CommandResponse.completed_at:type_name -> hexen.common.Timestamp
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_proto_command_command_proto_init() }
func file_proto_command_command_proto_init() {
	if File_proto_command_command_proto != nil {
		return
	}
	file_proto_command_command_proto_msgTypes[0].OneofWrappers = []any{
		(*Command_Shell)(nil),
		(*Command_FileOp)(nil),
		(*Command_ProcessKill)(nil),
		(*Command_Isolation)(nil),
		(*Command_Osquery)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_command_command_proto_rawDesc), len(file_proto_command_command_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_command_command_proto_goTypes,
		DependencyIndexes: file_proto_command_command_proto_depIdxs,
		EnumInfos:         file_proto_command_command_proto_enumTypes,
		MessageInfos:      file_proto_command_command_proto_msgTypes,
	}.Build()
	File_proto_command_command_proto = out.File
	file_proto_command_command_proto_goTypes = nil
	file_proto_command_command_proto_depIdxs = nil
}
